### PR TITLE
[react-i18n] Update currencies

### PR DESCRIPTION
**Pull request by cejaekl**
## Description

Fixes: https://github.com/Shopify/quilt/issues/1631

The list of currencies in `Shopify/quilt` has not been kept in sync with the list in `Shopify/shopify`.  After reviewing the two lists, I've identified a handful of codes that need to be included so that we have the same version of "the truth" in both places.

New currencies:
  - `BYN` Belarusia New Ruble
  - `BMD` Bermuda Dollar (pegged 1:1 to USD)
  - `DJF` Djibouti Franc
  - `ERN` Eritrea Nakfa
  - `FKP` Falkland Islands Pound (pegged 1:1 to GBP)
  - `GIP` Gibraltar Pound (pegged 1:1 to GBP)
  - `GNF' Guinea Franc
  - `IRR` Iran Rial
  - `KID` Kiribati Dollar (pegged 1:1 to AUD)
  - `LYD` Libya Dinar
  - `MRU` Mauritania New (Second) Ouguiya
  - `PAB` Panama Balboa
  - `SHP` Saint Helena Pound (pegged 1:1 to GBP)
  - `SLL` Sierra Leone Leone
  - `SOS` Somalia Shilling (a fiat currency that is unique because it's no longer backed by a central bank)
  - `TJS` Tajikistan Simoni
  - `TOP` Tonga Pa'anga
  - `VES` Venezuelan Sovereign Bolivar

Historical currencies that are being removed:
  - `BYR` Belarusia (Old) Ruble (replaced by `BYN`)
  - `VEF` Venezuealan Strong Bolivar (replaced by `VES`)

## Type of change

- [X] `react-i18n` Patch: Bug (non-breaking change which fixes an issue)

## Checklist

- [x] I have added a changelog entry, prefixed by the type of change noted above (Documentation fix and Test update does not need a changelog as we do not publish new version)

### CODE REVIEW

**Review by atesgoral — APPROVED** [review]

**Review by plentz — COMMENTED** [review]
Do we know what's the impact of removing `BYR`, `VES`, and `GIP` from this list? any backfill that we need to run?

**Comment by alexandcote** [comment]
GIP is still in the list, but I have the same question for `BYR` and `VES`. My other question is can we share this list somewhere so both shopify and quilt can use the share values?

**Comment by atesgoral** [comment]
@alexandcote Great idea. Let's discuss different ways that could be achieved. I'm thinking:

a. We spin up a shopify-currencies repo that publishes both a gem and an npm package
b. Both shopify and quilt use an already-existing source of truth (like an ISO currencies package -- but then we need both a gem and an npm package, unless shopify can pull from npm during build)

**Comment by cejaekl** [comment]
> @alexandcote Great idea. Let's discuss different ways that could be achieved. I'm thinking:
> 
> a. We spin up a shopify-currencies repo that publishes both a gem and an npm package
> b. Both shopify and quilt use an already-existing source of truth (like an ISO currencies package -- but then we need both a gem and an npm package, unless shopify can pull from npm during build)

The `shopify-i18n` gem already has a [list of currencies](https://github.com/shopify/shopify-i18n/#--currency-support).
This list is accessible via `country-service` ([PR](https://github.com/Shopify/country-service/pull/459)).

Things still on our [to-do list](https://github.com/Shopify/intl-globalization/issues/222):
  - allow selection of different currency lists (all known, only currencies that are currently in use, only currencies that can be used with Shopify Pay, top "most common" currencies).
  - update country-service to allow passing that sub-list selection through

**Review by plentz — APPROVED** [review]

**Review by rafaelxy — APPROVED** [review]

**Pull request merged**
