### PR TITLE
Add optional prop to <FormState.Nested> and <FormState.List> to re-render

### PR DESCRIPTION
**Pull request by amireynoso**
## What's the problem
As described in #557, `<FormState.Nested>` and `<FormState.List>` are not updating their children, unless the passed `field` changes.

While this is the expected behaviour (introduced in #312 to improve the performance of these components), there are cases in which it's necessary for the children to be updated. For example, if any of the child form elements also depend on a state change or a prop other than `field` changing.

## How it's solved
I considered changing the logic within `shouldComponentUpdate`, but ended up going with a non-intrusive solution:

- ✨ Added a new prop `update` to both `<FormState.Nested>` and `<FormState.List>`
   - `update` is optional, therefore falsy by default.
   - Setting this to `true` will by-pass the logic in `shouldComponentUpdate`
- ✅ Added new tests to cover the use of this prop
- 📝 Added info to the docs on why the children don't update (which could be unexpected) and instructions on how to use the prop

## Tophatting 🎩

I tophatted the changes in my app using `yarn tophat`. I'd recommend testing this in any app that's using either `<FormState.Nested>` or `<FormState.List>` and making sure that by using `update`, the child form elements get re-rendered. 

The tests should cover this case and can also be used as a playground to 🎩 it!

### CODE REVIEW

**Comment by michelleyschen** [comment]
I am having a hard time seeing how this will work - for example Pat's use case of the children should re-render when the modalVisible change.

Can you provided an example code?

**Comment by amireynoso** [comment]
Hey @michelleyschen! You'd use it like this:

```
<FormState.Nested field={fields.variants} update>
  {fields => (
    <>
      <TextField label="Option" {...fields.option} />
      <TextField label="Value" {...fields.value} />
    </>
  )}
</FormState.List>
```

By setting `update` (on either `<FormState.Nested>` or `<FormState.List>`), you're opting out completely of the performance checks that prevent these components to render if the passed `field` has not changed.

Considering that there could be many cases in which you'd want children to update, I thought it'd be better to just allow it to be turned off.

On the case I described in #557, my component should re-render on 2 different prop changes, and in Pat's case, it's a state change. 🤔I'm not sure how to make it smart enough to allow re-render for specific prop/state changes.

**Comment by michelleyschen** [comment]
ok I see, ya this make sense for the time being.

**Comment by lemonmade** [comment]
Hmm, I am not sure this really does what we need. Most likely, I think we should just revert back to using regular `PureComponent`s for these, because it is very unexpected that they would stop an update from happening that has nothing to do with them. If we don't want that, then `update` should at least be a prop we could pass an arbitrary string to; right now, it would be very hard to tell the component to `update`, then `update` again, because you will need to flip it to false/ undefined in between.

**Comment by patsissons** [comment]
the `update` flag should just be opting out of the standard _should update_ logic. maybe the flag name could be changed to be more representative, like `skipUpdateCheck` (ugh, naming things is hard).

**Comment by lemonmade** [comment]
But this is just not a thing you should need. I don't think we should keep performance optimizations that simply break React updates.

**Comment by patsissons** [comment]
ah i see, you're suggesting to just remove the attempt at optimizing perf altogether. Seems reasonable.

**Comment by amireynoso** [comment]
@lemonmade Thanks for your input! I was wondering about this too at the beginning. When it was first introduced in #312, it seemed to be a legitimate concern for some implementations, so, as to not introduce breaking changes, I thought we should at least provide a way to opt-out of it.

I merged but haven't released yet as I was pulled into a meeting. Should I just revert this PR, and open a new one removing `shouldComponentUpdate` for both components? Would that then be a major release?

**Comment by lemonmade** [comment]
I would prefer to revert and remove the `shouldComponentUpdate`, if we want to it's easy enough to go back to this, but adding this and removing it is a breaking change (removing `shouldComponentUpdate` is fine, since it's just an internal optimization and no one should be depending on it(

**Comment by amireynoso** [comment]
That makes sense! Thanks, @lemonmade. 

I opened https://github.com/Shopify/quilt/pull/564 reverting this PR (do I need approvals for that, or I can just go ahead and merge?). I will open a new PR removing the logic in `shouldComponentUpdate` early next week.

**Pull request merged**
