### PR TITLE
Add types support like in koa

### PR DESCRIPTION
**Pull request by polRk**
## should add type support like Koa. It's simple example with correct typings

- [+] jest-koa-mocks Minor: add better typings

### CODE REVIEW

**Comment by GoodForOneFare** [comment]
Hi, Vladislav!  Thank you for your contribution.  Could you take a look at fixing the CI failure in this branch, please?  It looks like it's related to the types that you're altering:

```
lerna ERR! $ tsc --p tsconfig.build.json
lerna ERR! src/create-mock-context/create-mock-context.ts(19,15): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
lerna ERR! src/create-mock-context/index.ts(1,8): error TS1192: Module '"/home/travis/build/Shopify/quilt/packages/jest-koa-mocks/src/create-mock-context/create-mock-context"' has no default export.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If you could sign the CLA, too, that you be really helpful 👍

**Comment by GoodForOneFare** [comment]
@vsumner - I'm on vacation for a bit.  Since you're already poking at this package, could you shepherd this through, please? 😸

**Comment by polRk** [comment]
If you could sign the CLA, too, that you be really helpful 👍

Yet

**Comment by polRk** [comment]
I using Koa mock context in my tests. And it's my example
```
import * as httpMocks from 'node-mocks-http'
import * as Koa from 'koa'

export interface MockContext<RequestBody = undefined> extends Koa.Context {
  request: Koa.Context['request'] & {
    body?: RequestBody
  }
}

export const koaMockContext = <
  State = Koa.DefaultState,
  Context = MockContext,
  RequestBody = undefined
>(
  requestBody?: RequestBody
) => {
  const req = httpMocks.createRequest()
  const res = httpMocks.createResponse()
  const app = new Koa<State, Context>()
  const context = app.createContext(req, res) as MockContext<RequestBody> & Koa.ParameterizedContext<State, Context>
  res.statusCode = 404
  context.request.body = requestBody
  return context
}
```

**Pull request closed without merging**
