### PR TITLE
[react-form] Remove `useMountedRef` check in useSubmit

### LINKED ISSUE #2500: [@shopify/react-form] `form.submitErrors` is not populated  when returning `{status: "fail"}`
## Overview

In a very simple example `submitErrors` is not populated.

## Consuming repo

> What repo were you working in when this issue occurred?

Made a reproducable example. https://stackblitz.com/edit/vitejs-vite-qctwdk?file=src/App.tsx

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

### PR DESCRIPTION
**Pull request by jokull**
## Description

Fixes #2500 and #2508 - maybe more things related to `useSubmit`

I believe the early exit inside `submit` is being triggered unwantingly in Next.js environments. This is a fix for that, but I'm not sure if it is then a regression for other scenarios.

### CODE REVIEW

**Comment by BPScott** [comment]
@jokull, are you able to produce a test case that fails without this change but passes with the change? I am wary of merging this change without proof that it fixes an issue and doesn't produce regressions in react 17.

**Comment by jokull** [comment]
This is no longer needed in Next 13.2.

**Comment by jamalsoueidan** [comment]
You can try it on vite + react fresh setup, it's still a problem.

**Comment by jamalsoueidan** [comment]
strict mode is breaking it!

**Pull request closed without merging**
