### PR TITLE
Update Slack channel

### LINKED ISSUE #1816: Slack channel in README `#web-foundation-tech` no longer exists
As subject.

### PR DESCRIPTION
**Pull request by andyw8**
Closes #1816

### CODE REVIEW

**Comment by andyw8** [comment]
I noticed that CI failing, will that cause problems?

**Comment by atesgoral** [comment]
Oof. TIL:

> The root README has not been updated. Run 'yarn generate docs' in the root of your Quilt directory and try again.

I'll patch it up.

**Comment by atesgoral** [comment]
@andyw8 We're already dealing with some test flakiness, so I assumed it was that :)

**Comment by andyw8** [comment]
This CI job took 6 hours to run? 😮 

https://github.com/Shopify/quilt/actions/runs/722894627

**Comment by atesgoral** [comment]
@andyw8 flaky, slow tests. We disabled them all for now.

**Pull request merged**
