### PR TITLE
Fix doc to give more proper example for pluralization 

### PR DESCRIPTION
**Pull request by iCynara**
## Description
Fix examples

### CODE REVIEW

**Review by tayre — APPROVED** [review]
Lgtm

**Review by trishrempel — APPROVED** [review]

**Review by sjahu — APPROVED** [review]
Looks good. I was initially concerned that the calling code wouldn't know what to do with the new keys, but [under the hood](https://github.com/Shopify/online-store-ui/blob/73135aa3df446da9b98c0d0cb4e643841b571aef/src/components/DateTime/DateTime.tsx#L34) it's just making a regular i18n.translate call so it should work just fine. Nice fix

**Comment by sjahu** [comment]
Hmmm, actually is what I just wrote true? @vsumner . Don't you need the `count` variable to be named for pluralization to work?

https://github.com/Shopify/online-store-ui/blob/73135aa3df446da9b98c0d0cb4e643841b571aef/src/components/DateTime/DateTime.tsx#L37

**Comment by iCynara** [comment]
oh right, it just need a merge, but the button is grey out for me, do i need permission or something? @vsumner

**Pull request merged**
