### PR TITLE
fixed missing ctx in readme

### PR DESCRIPTION
**Pull request by passionkind**
There was a missing `ctx` in the application route

### CODE REVIEW

**Comment by TheMallen** [comment]
Thanks!

**Comment by TheMallen** [comment]
@passionkind  what's up with the new commit? Is it addressing a different issue?

**Comment by passionkind** [comment]
@TheMallen please ignore the second commit. Only the readme fix. I committed the accessToken change by accident

**Comment by passionkind** [comment]
@TheMallen close this one and use this PR https://github.com/Shopify/quilt/pull/331

couldn't revert anymore

**Pull request closed without merging**
