### PR TITLE
Add linting for full lodash package

### PR DESCRIPTION
**Pull request by theodoretan**
Closes https://github.com/Shopify/quilt/issues/337

We want to restrict importing the entire lodash package.

Errors:
screen shot 2018-10-24 at 5 04 00 pm

No Errors:
screen shot 2018-10-24 at 5 07 52 pm

### CODE REVIEW

**Comment by TheMallen** [comment]
Hmmm, seems like this is exploding in CI?

**Comment by theodoretan** [comment]
Yeah 🤔

```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at left.type.Identifier.left.type.ArrayPattern.left.elements.some (/home/travis/build/Shopify/quilt/node_modules/eslint-plugin-shopify/lib/rules/restrict-full-import.js:42:26)
```

Did some digging and it looks like it’s coming from here because first value is blank.
https://github.com/Shopify/quilt/blob/56106636699ef57fed8eac9403ecbe7c9a86b78a/packages/dates/src/parse-date-string.ts#L20-L32

**Comment by TheMallen** [comment]
Might as well change that here, it won't effect any functionality :)

**Comment by TheMallen** [comment]
Still seeing an error in CI, I think you can fix it by changing it from `_` to any `_` prefixed name like `_unused`. If that doesn't work you can just put a `// @ts-ignore` right above the offending line.

**Comment by theodoretan** [comment]
🙌 Thanks!

**Pull request merged**
