### PR TITLE
[react-hooks] useOnValueChange odd interaction with setState

### PR DESCRIPTION
**Pull request by qw-in**
## Description

Currently, any call to `setState` within the `useOnValueChange` callback will only be available in one render

[Codesandbox demo](https://codesandbox.io/s/shopify-useonvaluechange-behaviour-bgyeg)

Fixes (issue #)

## Type of change

- [X]  Patch: Bug/ Documentation fix (non-breaking change which fixes an issue or adds documentation)

## Checklist

- [x] I have added a changelog entry, prefixed by the type of change noted above

### CODE REVIEW

**Comment by qw-in** [comment]
Just signed the CLA

**Comment by qw-in** [comment]
Closing since this is being addressed in #1351

**Comment by alexandcote** [comment]
@qw-in Thank you for your contribution 🎉. Sorry I didn't see your PR before I open mine 😬

**Comment by qw-in** [comment]
@alexandcote just happy to have it fixed :smile:

**Pull request closed without merging**
