### PR TITLE
Replace country-service with atlas

### PR DESCRIPTION
**Pull request by rebeccaqu**
## Description

`country-service` will be deprecated in favour of `atlas` (with no changes in functionality)

Link to issue: https://github.com/Shopify/atlas/issues/175

## Type of change

- [x]  Patch: Bug (non-breaking change which fixes an issue)
- [ ]  Minor: New feature (non-breaking change which adds functionality)
- [ ]  Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have added a changelog entry, prefixed by the type of change noted above (Documentation fix and Test update does not need a changelog as we do not publish new version)

### CODE REVIEW

**Comment by atesgoral** [comment]
@rebeccaqu A CHANGELOG entry for this update is needed. (This will probably be a patch when we cut a version.)

Please add a ["Changed"](https://keepachangelog.com/en/1.0.0/) entry in https://github.com/Shopify/quilt/blob/main/packages/address-consts/CHANGELOG.md

**Comment by rebeccaqu** [comment]
Hey @atesgoral 👋  - thanks for the heads up! 

I've checked off "patch" and added to the changelog - do you know when the next version cut will be?

**Review by atesgoral — APPROVED** [review]

**Comment by rebeccaqu** [comment]
> @rebeccaqu Soon! Perhaps tomorrow, the latest.

@atesgoral amazing 🤞

**Comment by atesgoral** [comment]
@rebeccaqu `@shopify/address-consts@3.0.2` released!

**Comment by GoodForOneFare** [comment]
IMO, this should have been a major version change. cc @Shopify/checkout-one-frontend - if C1 is still using `@shopify/addresses`, an upgrade will require CSP changes in core.

**Pull request merged**
