### PR TITLE
[koa-shopify-auth] restore prefix support

### PR DESCRIPTION
**Pull request by kavika-1**
## Description

Fixes [#1148][#1426]

Apply prefix in koa-shopify-auth to various Safari/ITP redirects.

[#1413] addresses several issues with Safari by bringing in some code from `shopify_app`.  However, that code was not `koa-shopify-auth` `prefix` aware.  This small set of changes helps address this.

NOTE: There are similar PRs [#1149] and [#1196], hopefully this simply addresses the same issue post [#1413].  Supercedes [#1428].

Quick discussion: While most of the redirects are related to prefixing "/auth" routes, there is one additional target, `appTargetUrl`, to which the prefix could be added to as well, since otherwise, upon client side redirect, the server has no idea where this came from.  Note that the referer (sic) header is now blocked on safari, and even with the Referrer-Policy set, only the origin is provided not the path, so even that method cannot be used to infer the prefix upon return.

## Type of change

- [x] koa-shopify-auth Patch: Bug/ Documentation fix (non-breaking change which fixes an issue or adds documentation)

## Checklist

- [x] I have added a changelog entry, prefixed by the type of change noted above

### CODE REVIEW

**Comment by simonhaenisch** [comment]
I agree with @ragalie that the prefix shouldn’t apply to `appTargetUrl`. E. g. my prefix is `/api` (requirement of Next.js API routes), but the app lives under `/` and sending the user to `/api` would result in a 404.

**Comment by ragalie** [comment]
Thanks @kavika-1!

One last thing to do is to complete that checklist item ("I have added a changelog entry"). You can edit the `CHANGELOG.md` file in this repo. You'll notice there's a commented out "Unreleased" section. You'll want to uncomment that and put your changelog entry under there. For example:

```
## [Unreleased]
### Fixed
- Include `prefix` when we redirect to the `/auth` path.
```

**Comment by kavika-1** [comment]
@ragalie thanks for the instructions, done.  @simonhaenisch appreciate your comments, and support for getting "our" fix in.  cheers.

**Comment by ragalie** [comment]
Just rounding up another review today and then we should be good to get this merged in. Thanks again for the contribution!

**Comment by tanema** [comment]
I have tophatted this now as well! Good to go

**Comment by ayronshopify** [comment]
Hey @kavika-1, do you mind rebasing this from master and squashing your commits, and then we can merge 🚢

**Comment by simonhaenisch** [comment]
Do you always make it this hard for first-time contributors to fix your software for you? 🙄

Why not just squash-merge this PR (after merging master again which has no merge-conflicts from what I can tell)? 🤷🏻‍♂️

**Comment by ayronshopify** [comment]
Thanks @simonhaenisch, squash-merge isn't an option for me on this repo and I didn't want to overwrite @kavika-1's contributions by squashing myself. Plus tbh, I'm not entirely sure how to squash/rebase back to his fork, as I only have the option to create a new branch on `/quilt` which would definitely overwrite his contribution. 

image

**Comment by tanema** [comment]
> Do you always make it this hard for first-time contributors to fix your software for you? 🙄
> 
> Why not just squash-merge this PR (after merging master again which has no merge-conflicts from what I can tell)? 🤷🏻‍♂️

@simonhaenisch please watch how you speak on this repo. The contributor was asked to comply with our best practices and if it was unclear then help should be requested. Please review our COC https://github.com/Shopify/quilt/blob/master/.github/CODE_OF_CONDUCT.md

Please keep this in mind the next time you engage with our open source repos.

**Comment by simonhaenisch** [comment]
I apologize, @ayronshopify, I was under the assumption that @kavika-1 had ticked the "allow edits from maintainers" option for this PR (which would give you permission to make commits to the PR's compare branch).

---

Cheers @tanema... from your link:

> Gracefully accepting constructive criticism

I'll expand a bit so my comment is more constructive: After I opened an issue for this package three weeks ago that even included a suggested fix, I have still not yet gotten as much as a response, which is why I've started looking through the other issues and PRs for this package before making a PR myself... and noticed there is not much engagement from the team with a few exceptions (e. g. TheMallen). A partial fix for this issue was created half a year ago and reading through the issue comments speaks for itself: #1148 (tl;dr people get frustrated).

Now there's this PR, a perfect fix for this bug, tests and everything... he's basically doing some work for your team for free, which is kind of the point of open-sourcing. We benefit from your software and you benefit from our contributions. But IMO you make it quite difficult for his fix to land in your code? The code reviews for effectively 9 changed lines of code took 5 days and that's after the first PR #1428 (with CLA and rebasing issues) had been approved already, which also took 3 days. Whether a CLA is necessary in a MIT licensed project is another discussion, but mentioning its existence and requirements (i. e. that it reads the contributor's email address from the commit) in `CONTRIBUTING.md` probably would have been helpful to @kavika-1. Even better, you could add a checklist as a pull request template, to help especially first-time contributors (that would include people joining your team as well).

Personally (just from reading through issues and PRs), at this point I'd rather maintain a fork than contributing under these conditions. That's why I ended up copying this package and publishing it to npm under my own scope. There's some fixes that I actually needed for our app and we didn't have the time to wait for maybe months.

I hope this feedback comes across as a somewhat helpful reflection, and that going forward community contributions for this package (including bug reports) get some more priority.

**Comment by kavika-1** [comment]
Ok, i pushed the github button, and waited for tests to complete.  All items green, thanks for the support and guidance.

Regarding **Allow edits from maintainers**, i must be seriously dense because i do not see that checkbox on this pull request.  Referring to this: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Pull request merged**
